project_name: "Sport booking"

server:
    env: development # development, production
    host: "0.0.0.0"
    port: 3000
    cert_file: "./certs/cert.pem"
    key_file: "./certs/key.pem"
    debug: false

cors:
    allow_origin:
        - "https://127.0.0.1:3001"
    allow_headers:
        - "Content-Type"
        - "Origin"
        - "Accept"
        - "Authorization"
    allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
    allow_credentials: true

jwt:
    secret: "1234balhblahblah"
    access_token_exp: 150 # minutes
    refresh_token_exp: 43200 # minutes
    expire_cache: 43200 # minutes

oauth:
    google:
        client_id: "12163156491-vec0etdic5l77r6po4qfvl3h4e30gj2v.apps.googleusercontent.com"
        client_callback: "/api/auth/google/callback"

database:
    engine: "postgres"
    postgres:
        host: "spb-booking.ctcu6o22mk8d.ap-southeast-1.rds.amazonaws.com"
        port: "5432"
        user: "spb_user"
        password: "spb_password"
        dbname: "spb_database"
        ssl_mode: "require"

redis:
    addrs:
        - "localhost:6379"
    password: "spb_password"
    username: ""
    reset: false
    pool_size: 10
    db: 0

logging:
    level: 0 # debug:0, info:1, warning:2, error:3
    output:
        - "console"
        - "file"
    filename: "requests.log"

aws:
    region: "ap-southeast-1"
    max_retries: 3

notification:
    ios:
        enabled: false
    android:
        enabled: false
    redis_queue:
        channel_name: "notification"
        channel_size: 10
        worker_num: 4

payment:
    momo:
        partner_code: "MOMO_PARTNER_CODE"
        access_key: "MOMO_ACCESS_KEY"
        secret_key: "MOMO_SECRET_KEY"
        endpoint: "https://test-payment.momo.vn/v2/gateway/api/create"
        return_url: "https://your-return-url.com"
        notify_url: "https://your-notify-url.com"
    zalopay:
        app_id: 2554
        key1: "sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn"
        key2: "trMrHtvjo6myautxDUiAcYsVtaeQ8nhf"
        endpoint: "https://sb-openapi.zalopay.vn"
        callback_url: "https://duties-rug-detected-merchant.trycloudflare.com/api/v1/orders/zalopay/callback"
        redirect_url: ""

order:
    multiple_time: 30 # minutes

otp:
    length: 4
    expire: 2 # minutes
